## Web-Scraping Indeed.com
This script is created to scrape relevant jobs from indeed.com, using the libraries, Selenium and bs4

In [2]:
import numpy as np
import pandas as pd

from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.alert import Alert

from time import sleep

import html2text

In [120]:
h = html2text.HTML2Text()
h.ignore_links = True

In [21]:
job_data = []

In [22]:
for title in ['data analyst','data scientist', 'business intelligence data']:
    
    url = ('https://www.indeed.com.sg/')
    driver = webdriver.Chrome(executable_path='/Users/user/Documents/GA-DSI/course-materials/classes/week-06/labs/python-webscraping_opentable-lab-master/chromedriver/chromedriver_1')

    driver.get(url)

    ## Keying in search term

    search_term = driver.find_element_by_id('text-input-what')
    search_term.send_keys(title)

    sleep(np.random.randint(1,5))

    driver.find_element_by_xpath('//*[@id="whatWhere"]/form/div[3]/button').click()
    default_handle=driver.current_window_handle


    for page in np.arange(10):
        print 'this is page ', page
        
        for i in np.arange(0,15):
            print i
            this_job = {}
            sleep(np.random.randint(1,4))
            try:
                driver.find_element_by_class_name('popover-x-button-close').click()   ## in case of popup dialog, this will close box 
            except:
                pass

            try:
                try:
                    driver.find_elements_by_class_name('jobtitle')[i].click()
                    print i,'job click suc'
                except:
                    print i,'job click fail'
                    continue
                driver.switch_to_window(driver.window_handles[1])

                sleep(np.random.randint(2,4))

                            ## Extracting the data required

                HTML = driver.page_source
                soup = BeautifulSoup(HTML,'lxml')
                try:
                    this_job['job_title'] = soup.find('b',{'class':'jobtitle'}).text ## Job title
                    print i,' title ext suc'
                except:    
                    this_job['job_title'] = soup.find('h3',{'class':'jobsearch-JobInfoHeader-title'}).text
                    print i,' title ext suc'
                try:
                    this_job['salary'] = soup.find('span',{'class':'no-wrap'}).text ## Salary
                    print i,' salary ext suc'
                except:
                    pass
                this_job['company'] = soup.find('span',{'class':'company'}).text ## Company
                print i,' comp ext suc'
                this_job['jd'] = soup.find('span',{'id':'job_summary'}).text ## Getting the job description
                print i,' jd ext suc'

                job_data.append(this_job)

                sleep(np.random.randint(3,5))

                            ## Close current listed job page and return to main page with all the other listings

                driver.close()
                driver.switch_to_window(default_handle)
                print i            

            except:
                print 'error',i


        ## Goto next page
        try:
            driver.find_elements_by_class_name('np')[-1].click()
            print 'next page',page
        except:
            print 'next page fail',page
            driver.close()
            break

this is page  0
0
0 job click suc
0  title ext suc
0  salary ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  salary ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 0
this is page  1
0
0 job click suc
0  title ext suc
0  salary ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  salary ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  salary ext suc
14  comp ext suc
14  jd ext suc
14
next page 1
this is page  2
0
0 job click suc
0  title ext suc
0  salary ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  salary ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  salary ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 2
this is page  3
0
0 job click suc
0  title ext suc
0  salary ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  salary ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  salary ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  salary ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  salary ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  salary ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  salary ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  salary ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 3
this is page  4
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  salary ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  salary ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  salary ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  salary ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  salary ext suc
14  comp ext suc
14  jd ext suc
14
next page 4
this is page  5
0
0 job click suc
0  title ext suc
0  salary ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  salary ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  salary ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 5
this is page  6
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  salary ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  salary ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 6
this is page  7
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc

1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  salary ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  salary ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  salary ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  salary ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  salary ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 7
this is page  8
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  salary ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  salary ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  salary ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 8
this is page  9
0
0 job click suc
0  title ext suc
0  salary ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  salary ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  salary ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  salary ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  salary ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 9
this is page  0
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 0
this is page  1
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  salary ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  salary ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  salary ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  salary ext suc
14  comp ext suc
14  jd ext suc
14
next page 1
this is page  2
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  salary ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  salary ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  salary ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 2
this is page  3
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  salary ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  salary ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  salary ext suc
14  comp ext suc
14  jd ext suc
14
next page 3
this is page  4
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc

5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  salary ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 4
this is page  5
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  salary ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  salary ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 5
this is page  6
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  salary ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 6
this is page  7
0
0 job click suc
0  title ext suc
0  salary ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  salary ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  salary ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  salary ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 7
this is page  8
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 8
this is page  9
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  salary ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  salary ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 9
this is page  0
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  salary ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  salary ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  salary ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  salary ext suc
14  comp ext suc
14  jd ext suc
14
next page 0
this is page  1
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  salary ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  salary ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  salary ext suc
11  comp ext suc
11  jd ext suc

11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  salary ext suc
14  comp ext suc
14  jd ext suc
14
next page 1
this is page  2
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
9  title ext suc
9  comp ext suc
9  jd ext suc
9
10
10 job click suc
10  title ext suc
10  salary ext suc
10  comp ext suc
10  jd ext suc
10
11
11 job click suc
11  title ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 2
this is page  3
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  salary ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
error 5
6
6 job click suc
error 6
7
7 job click suc
error 7
8
8 job click suc
error 8
9
9 job click suc
error 9
10
10 job click suc
error 10
11
11 job click suc
11  title ext suc
11  salary ext suc
11  comp ext suc
11  jd ext suc
11
12
12 job click suc
12  title ext suc
12  comp ext suc
12  jd ext suc
12
13
13 job click suc
13  title ext suc
13  salary ext suc
13  comp ext suc
13  jd ext suc
13
14
14 job click suc
14  title ext suc
14  comp ext suc
14  jd ext suc
14
next page 3
this is page  4
0
0 job click suc
0  title ext suc
0  comp ext suc
0  jd ext suc
0
1
1 job click suc
1  title ext suc
1  comp ext suc
1  jd ext suc
1
2
2 job click suc
2  title ext suc
2  comp ext suc
2  jd ext suc
2
3
3 job click suc
3  title ext suc
3  salary ext suc
3  comp ext suc
3  jd ext suc
3
4
4 job click suc
4  title ext suc
4  comp ext suc
4  jd ext suc
4
5
5 job click suc
5  title ext suc
5  comp ext suc
5  jd ext suc
5
6
6 job click suc
6  title ext suc
6  comp ext suc
6  jd ext suc
6
7
7 job click suc
7  title ext suc
7  salary ext suc
7  comp ext suc
7  jd ext suc
7
8
8 job click suc
8  title ext suc
8  comp ext suc
8  jd ext suc
8
9
9 job click suc
error 9
10
10 job click fail
11
11 job click fail
12
12 job click fail
13
13 job click fail
14
14 job click fail
next page fail 4

-----------

### Loading scraped job data to a dataframe

In [23]:
df = pd.DataFrame(job_data)

In [24]:
df

,company,jd,job_title,salary
0,Collabera,Job SummaryAbout the client: A global bank pro...,Data Analyst,"\n $5,000 a month -"
1,Dow Jones,Job Description:\nThe Data Solutions team is i...,"AML Analyst, Data Solutions, English & Chinese...","Full-time, Permanent"
2,Collabera,Job SummaryAbout the client: A global bank pro...,AML Analyst,"\n $4,500 a month -"
3,Xpand Group,Responsibilities\nConduct exploratory workshop...,Senior Data Analyst - Analytics Incubation,NaN
4,Apple,Apple’s Strategic Data Solutions (SDS) team le...,Data Science Analyst,NaN
5,Kpler,The role will involve maintaining the highest ...,Junior Data Analyst,NaN
6,SGX,Short overview on the Unit/Team\n\n Business M...,Data Analyst,NaN
7,Siemens AG,Responsibilities:\nYour new role – challenging...,Data Analyst,NaN
8,Traveloka,Data Analyst at Traveloka is at the forefront ...,Data Analyst,NaN
9,Clariant,Clariant is a globally leading specialty chemi...,Data Analyst,NaN
10,FinAccel,Responsibilities:\nThe Data Analyst analyzes h...,Data Analyst,NaN
11,Chope,We are looking for a Data Analyst to join our ...,Data Analyst,NaN
12,Grab Taxi,Get to know our Team:\nGrab’s Regional Data Sc...,Data Analyst,NaN
13,Haulio Pte Ltd,"As a member of Haulio’s Business Analyst team,...",Data Analyst,NaN
14,Dow Jones,Job Description:\nThe role of the Quality Anal...,Lists Assurance Quality Analyst,NaN
15,Collabera,About the client: A leading social media platf...,Operation Analyst - Ticketing Experience,"\n $4,000 a month -"
16,Dow Jones,Job Description:\nThe role of the Quality Anal...,Lists Assurance Quality Analyst,NaN
17,Xpand Group,Responsibilities\nConduct exploratory workshop...,Senior Data Analyst - Analytics Incubation,NaN
18,Traveloka,Job Description\n\nData Analyst at Traveloka i...,Data Analyst,NaN
19,Ubisoft,Job Description\n\nResponsibilities of the rol...,Data Analyst,NaN
20,Digital Alchemy,Digital Alchemy’s Data Science team is chiefly...,Data Analyst,NaN
21,MatchMove Global Pte Ltd,"MatchMove Pay, one of the fastest, award-winni...",Data Analyst,NaN
22,HP,Data Analyst\n\nHP is the world’s leading pers...,Data Analyst,NaN
23,DXC,Job Description:\nSummary\nAssists in the impl...,Assoc Prof:Data Analyst,NaN
24,Haulio,"As a member of Haulio’s Business Analyst team,...",Business / Data Analyst,NaN
25,United Overseas Bank,Functional area: Personal Financial Services (...,"Data Analyst, Digital Bank",NaN
26,Helius Technologies Pte Ltd,2-3 years of experience in SQL. Knowledge of S...,Data Analyst,"Full-time, Contract"
27,Monetary Authority of Singapore,Work with business and tech users to identify ...,Data Analyst (11-month contract),NaN
28,Dow Jones,Job Description:\nThe Data Solutions team is i...,"AML Analyst, Data Solutions, English & Chinese...","Full-time, Permanent"
29,Collabera,Job SummaryAbout the client: A global bank pro...,Data Analyst,"\n $5,000 a month -"
...,...,...,...,...
333,United Overseas Bank,Functional area: Data Management Office\n\nEmp...,"Vice President, Business Intelligence",NaN
334,Sciente,A well-known client in the financial sector is...,Project Manager (Business Intelligence),NaN
335,Amaris,Amaris is recruiting a Senior Business Intelli...,Senior Business Intelligence Consultant,NaN
336,JLL,We are currently seeking an Analyst-Business I...,Business Analyst - Business Intelligence/Data ...,NaN
337,United Overseas Bank,Functional area: Group Finance & Corporate Ser...,"VP/AVP, Business Intelligence, Group Finance",NaN
338,"Love, Bonito",DESCRIPTION\nThe Role\n\nYou’ll have front sea...,Business Intelligence Analyst,NaN
339,Grab Taxi,About the Role\nThe role is about leading the ...,"Manager, Market Research & Data Analytics",NaN
340,Lee Yin Apparel International Pte Ltd,Job Summary: The Business Intelligence (“BI”) ...,Business Intelligence Specialist,"\n $2,200 - $2,700 a month -"
341,The Learning Lab,The Learning Lab is a leading education centre...,Data Warehouse Architect (1 year contract),NaN
342,Mediacorp Pte Ltd,Serve as primary source of data insights suppo...,Data Scientist,NaN
343,Collabera,Job SummaryAbout the client: A global bank pro...,Data Analyst,"\n $5,000 a month -"
344,"Kaishi Partners, EA Licence No: 16C8316",Responsibilities/Roles\n\nOversee all activiti...,Head of Analytics (Business Intelligence),NaN
345,Accenture,Join Accenture and help transform leading orga...,Big Data Solution Architect,NaN
346,"Kaishi Partners, EA Licence No: 16C8316",Responsibilities/Roles\n\nOversee all activiti...,Head of Analytics (Business Intelligence),NaN
347,Bloomberg,Job Requisition Number:67433\n\nBloomberg is a...,Data Analyst - Electronic Trading Operations -...,NaN
348,mPlatform,Overview of job\n\nGroupM is the world’s large...,[m]Platform | Business Intelligence Analyst,NaN
349,BNP Paribas,Position Overview\nThis position is in the Dec...,Wealth Management - Business Intelligence Anal...,"Full-time, Contract, Permanent"
350,Infineon Technologies,In your new role you will:\nBe designing and b...,Contract - System Analyst - Business Intelligence,"Full-time, Temporary"
351,Alibaba,\nBuilding and automating reports and dashboar...,蚂蚁金服 Business Intelligence & Analytics expert ...,NaN
352,Collabera,Job SummarySupport sales teams with key planni...,Sales Analyst,Contract
353,Uber,About Uber\n\nWe’re changing the way people th...,Strategy & Planning Lead APAC,NaN
354,Accenture,Are you interested in working with the best an...,Analytics Consultant,NaN
355,Xpand Group,Our client's Data Science and Engineering team...,Tech Lead - Data Engineering,NaN
356,Bloomberg,Job Requisition Number:67433\n\nBloomberg is a...,Data Analyst - Electronic Trading Operations -...,NaN
357,Systems on Silicon Manufacturing Co. Pte. Ltd.,Responsibilities:\nSupport and development of ...,IT Engineer (Business Intelligence) - 1 Year C...,Contract
358,IQVIA,Join us on our exciting journey!\n\nIQVIA™ is ...,Site Strategy Intelligence Lead,NaN
359,Quintiles Transnational,PURPOSE\nResponsible for providing input into ...,Site Strategy Intelligence Lead,NaN
360,Amazon.com,Job Description\nAre you a Big Data specialist...,Specialist Solutions Architect - Big Data and ...,NaN
361,Singapore Tourism Board,To provide project management assistance and g...,"Contract Assistant Manager, Business Intellige...",Contract
362,Merck KGaA,The Manager actively partners with business le...,"Strategy & Intelligence Manager, APAC",NaN

In [26]:
## Conversion to json

df.to_json('./raw_data_jobs_indeed.json',orient ='records',force_ascii=False)